version: 2.1

orbs:
  node: circleci/node@5.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    executor: node/default
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b2:53:f8:5b:70:c5:ae:70:4a:54:9c:1c:c5:4f:ae:b1"
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run:
          name: install
          command: yarn install
      - run:
          name: Build app
          command: yarn build
