version: 2.1

orbs:
  node: circleci/node@5.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    executor: node/default
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - add_ssh_keys:
          fingerprints:
            - "45:a6:2f:a0:b5:62:85:c2:98:1a:20:d4:46:a8:d4:f6"
      - checkout
      - node/install:
          install-yarn: true
          node-version: "18.16"
      - restore_cache:
          keys:
            - v1-myapp-cache
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: v1-myapp-cache
          paths:
            - node_modules
      - run:
          name: Build app
          command: yarn build
      - run:
          name: Prepare shell commands
          # shell chmod +x 赋予执行权限
          # 执行shell脚本
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy to Github pages
          command: ./scripts/deploy.sh
